### ISSUE TITLE
The "webpage" button on Flathub does not redirect to the official site.

### ISSUE THREAD

**Issue by IngrownMink4** [flathub/net.sourceforge.GrandOrgue#18]
The URL has quotation marks at the end, which causes the URL to break, resulting in a 404 error. 
![017377107017](https://user-images.githubusercontent.com/25466522/156827846-f50807b0-0276-4ef3-a8eb-27905793d21e.png)
![6130915630961063](https://user-images.githubusercontent.com/25466522/156827850-c3574c7d-7d25-4c33-95c4-51e488d55c10.png)

Simply removing the quotation marks on line 32 would fix the problem:
https://github.com/flathub/net.sourceforge.GrandOrgue/blob/master/GrandOrgue.appdata.xml#L32

**Comment by lbssousa** [comment]
The homepage was updated in commit e5f20f7add2173025e7ffc8e83364e1027afa4ac
